// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNTYfHezZeLV4AmNb5QUkL5_u3J4x-YQQ',
    appId: '1:386682682612:web:007c1da5af4197611ab2a1',
    messagingSenderId: '386682682612',
    projectId: 'chat-app-6f6fa',
    authDomain: 'chat-app-6f6fa.firebaseapp.com',
    storageBucket: 'chat-app-6f6fa.firebasestorage.app',
    measurementId: 'G-PS878Q74B3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH_C6fnigFLw5-gYjWMW4N5V8q5ejnwmI',
    appId: '1:386682682612:android:48110efa6266ebef1ab2a1',
    messagingSenderId: '386682682612',
    projectId: 'chat-app-6f6fa',
    storageBucket: 'chat-app-6f6fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvv2XF4ZEkqnuqql7h-c3sCJddPUKC8vs',
    appId: '1:386682682612:ios:2d386016a94959651ab2a1',
    messagingSenderId: '386682682612',
    projectId: 'chat-app-6f6fa',
    storageBucket: 'chat-app-6f6fa.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvv2XF4ZEkqnuqql7h-c3sCJddPUKC8vs',
    appId: '1:386682682612:ios:2d386016a94959651ab2a1',
    messagingSenderId: '386682682612',
    projectId: 'chat-app-6f6fa',
    storageBucket: 'chat-app-6f6fa.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNTYfHezZeLV4AmNb5QUkL5_u3J4x-YQQ',
    appId: '1:386682682612:web:005391da6e31fc6e1ab2a1',
    messagingSenderId: '386682682612',
    projectId: 'chat-app-6f6fa',
    authDomain: 'chat-app-6f6fa.firebaseapp.com',
    storageBucket: 'chat-app-6f6fa.firebasestorage.app',
    measurementId: 'G-V8LY5M83G4',
  );
}
